'use strict';

exports.cropTypes = [
  {'cropType':'Avocado'},
  {'cropType':'Broccoli'},
  {'cropType':'Cabbage'},
  {'cropType':'Carrots'},
  {'cropType':'Cauliflower'},
  {'cropType':'Celery'},
  {'cropType':'Lettuce'},
  {'cropType':'Onion (dry)'},
  {'cropType':'Onion (green)'},
  {'cropType':'Onion (seed)'},
  {'cropType':'Spinach'},
  {'cropType':'Radish'},
  {'cropType':'Egg plant'},
  {'cropType':'Sweet peppers (bell)'},
  {'cropType':'Tomato'},
  {'cropType':'Cantaloupe'},
  {'cropType':'Cucumber'},
  {'cropType':'Pumpkin'},
  {'cropType':'Squash'},
  {'cropType':'Sweet melons'},
  {'cropType':'Cassava'},
  {'cropType':'Potato'},
  {'cropType':'Sweet potato'},
  {'cropType':'Beans (green)'},
  {'cropType':'Beans (dry)'},
  {'cropType':'Lentil'},
  {'cropType':'Peas'},
  {'cropType':'Soybeans'},
  {'cropType':'Artichoke'},
  {'cropType':'Asparagus'},
  {'cropType':'Cotton'},
  {'cropType':'Flax'},
  {'cropType':'Sesame'},
  {'cropType':'Sunflower'},
  {'cropType':'Barley'},
  {'cropType':'Maize (grain)'},
  {'cropType':'Maize (sweet)'},
  {'cropType':'Millet'},
  {'cropType':'Rice'},
  {'cropType':'Sugarcane'},
  {'cropType':'Banana, 1st yr'},
  {'cropType':'Banana, 2nd yr'},
  {'cropType':'Pineapple'},
  {'cropType':'Grapes'},
  {'cropType':'Hops'},
  {'cropType':'Citrus'},
  {'cropType':'Olives'}
];
