language: node_js
node_js:
  - '0.10'
before_script:
  - psql -c 'create database pragma_test;' -U postgres
  - 'npm install -g bower grunt-cli'
  - 'bower install --config.interactive=false'

cache:
  directories:
    - node_modules
    - 'app/bower_components'

notifications:
  email:
    - victor.reventos1@gmail.com
    - jose.diaz30@upr.edu
    - miguel.garcia9@upr.edu
